# Generated by Django 5.2.7 on 2025-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
