# Generated by Django 5.2.7 on 2025-12-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0004_study_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord_bot.discordguild')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordStudyMapping',
            fields=[
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studies.study')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_bot.discordchannel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discordchannel',
            constraint=models.UniqueConstraint(fields=('id', 'guild'), name='unique_guild_channel_mapping'),
        ),
        migrations.AddConstraint(
            model_name='discordstudymapping',
            constraint=models.UniqueConstraint(fields=('channel', 'study'), name='unique_guild_study_mapping'),
        ),
    ]
