# Generated by Django 5.2.7 on 2025-12-19 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordstudymapping',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_bot.discordguild'),
        ),
    ]
