"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&+gh+z#80sh=t116m4m(w7ae8am1ne3dkrh59a=mg8f8)lv_&@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '13.209.87.32',
    'localhost:8000',
    'localhost',
]

AUTH_USER_MODEL = 'accounts.User'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

from dotenv import load_dotenv
import os
load_dotenv()
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
VUE_API_URL = os.getenv("VUE_API_URL")
DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")
DISCORD_REDIRECT_URI = os.getenv("DISCORD_REDIRECT_URI")
DISCORD_REDIRECT_URI_FOR_LOGIN = os.getenv("DISCORD_REDIRECT_URI_FOR_LOGIN")
DISCORD_REDIRECT_URI_CONNECT_STUDY = os.getenv("DISCORD_REDIRECT_URI_CONNECT_STUDY")
DISCORD_PERMISSIONS = os.getenv("DISCORD_PERMISSIONS")
DISCORD_OAUTH_URL = os.getenv("DISCORD_OAUTH_URL")
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DB_PASSWORD = os.getenv("DB_PASSWORD")

# GMS
GMS_API_URL = os.getenv("GMS_API_URL")
GMS_KEY = os.getenv("GMS_KEY")
# Application definition

INSTALLED_APPS = [
    'main',
    'accounts',
    'studies',
    'posts',
    'schedules',
    'corsheaders',
    'discord_bot',
    'exams',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # 리프레시 토큰 블랙리스트 사용 시
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.discord',  # discord provider
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 필요시 DEFAULT_PERMISSION_CLASSES 등 추가
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # 로컬 로그인 유지
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
)

# allauth 기본 설정 (이메일 인증 등 필요시)
ACCOUNT_EMAIL_VERIFICATION = "none"  # 이메일 인증 불필요(요구사항)
SOCIALACCOUNT_PROVIDERS = {
    'discord': {
        'SCOPE': ['identify', 'email'],  # 이메일도 요청
        'APP': {
            'client_id': os.environ.get('DISCORD_CLIENT_ID'),
            'secret': os.environ.get('DISCORD_CLIENT_SECRET'),
            'key': ''
        }
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    # 기본값: ACCESS 5분, REFRESH 1일. 필요시 조정.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # 보안 권장: 리프레시 토큰 회전 및 블랙리스트 사용
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # 서명 알고리즘은 기본 HS256(SECRET_KEY) 사용
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "nestudy_db",
    #     "USER": "nestudy_user",
    #     "PASSWORD": DB_PASSWORD,
    #     "HOST": "db",
    #     "PORT": "5432",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Vue 개발 서버 (Vite default 포트)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    VUE_API_URL,
]

CORS_ALLOW_CREDENTIALS = True  # 세션/쿠키 인증 시 필수

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    VUE_API_URL,
]

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = "redis://redis:6379/1"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-reminders-every-minute': {
        'task': 'schedules.tasks.scan_and_send_reminders',
        'schedule': crontab(minute='*'),
    }
}