# Generated by Django 5.2.7 on 2025-12-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_reminder_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='has_reminders',
        ),
    ]
