# Generated by Django 5.2.7 on 2025-11-27 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_studymembership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studymembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studymembership',
            constraint=models.UniqueConstraint(fields=('user', 'study'), name='unique_user_study'),
        ),
    ]
