# Generated by Django 5.2.7 on 2025-12-02 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_studymembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_studies",
                through="studies.StudyMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
