# Generated by Django 5.2.7 on 2025-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="start_at",
            field=models.DateTimeField(
                blank=True,
                help_text="시험 입장 가능 시작 시각 (비워두면 바로 응시 가능)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="시험 응시 마감 시각 (비워두면 시간 제한 없음)",
                null=True,
            ),
        ),
    ]
