# Generated by Django 5.2.7 on 2025-12-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
        ('studies', '0003_alter_studymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='discordstudymapping',
            name='unique_guild_study_mapping',
        ),
        migrations.RemoveField(
            model_name='discordstudymapping',
            name='guild',
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.discordguild'),
        ),
        migrations.AddField(
            model_name='discordstudymapping',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discord.discordchannel'),
        ),
        migrations.AddConstraint(
            model_name='discordstudymapping',
            constraint=models.UniqueConstraint(fields=('channel', 'study'), name='unique_guild_study_mapping'),
        ),
        migrations.AddConstraint(
            model_name='discordchannel',
            constraint=models.UniqueConstraint(fields=('id', 'guild'), name='unique_guild_channel_mapping'),
        ),
    ]
